version: '3'
# 定义四个服务nginx,php,mysql,redis
services:
  nginx:
    # 依赖php服务，意味着在启动nginx之前先启动php
    depends_on:
      - php
      # nginx镜像的路径
    build: ./nginx
    privileged: true
        # 这样使nginx容器把网站文件和目录存放到主机目录中，持久化和方便管理
    volumes:
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./nginx/log:/var/log/nginx
        # nginx意外退出时自动重启
    restart: always
    environment:
      TZ: Asia/Shanghai
        # 映射80和443端口
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

        # 容器名称
    container_name: centos-nginx

  php:
    depends_on:
      - mysql
      - redis
    build: ./php71
    ports:
      - "9000"
    networks:
      - frontend
      - backend
    privileged: true
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./php71/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php71/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ./php71/php.ini:/usr/local/php/etc/php.ini
      - ./php71/log:/usr/local/php/var/log
      - ./nginx/www:/usr/share/nginx/html
      - ./php71/crontab/crontab:/etc/crontab
    restart: always
    container_name: centos-php71

  php56:
    depends_on:
      - mysql
      - redis
    build: ./php56
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9000"
    networks:
      - frontend
      - backend
    volumes:
      - ./php56/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php56/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ./php56/php.ini:/usr/local/php/etc/php.ini
      - ./php56/log:/usr/local/php/var/log
      - ./nginx/www:/usr/share/nginx/html
      - ./php56/crontab/crontab:/etc/crontab
    restart: always
    container_name: centos-php56
#    command: /usr/local/mongodb/bin/mongod --dbpath=/usr/local/mongodb/data --logpath=/usr/local/mongodb/logs --logappend  --port=27017 --fork
  # MySQL
  mysql:
    image: mysql:5.7
    ports:
      - "127.0.0.1:3306:3306"
    privileged: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    networks:
      - backend
    restart: always
    container_name: centos-mysql

  # REDIS
  redis:
    build: ./redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - backend      
    volumes:
      - ./redis/redis.conf:/usr/local/redis/redis.conf
      - ./redis/redis.log:/usr/local/redis/redis.log
    restart: always
    environment:
      TZ: Asia/Shanghai
    container_name: centos-redis

networks:
  frontend:
  backend:
